config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Point route to a controller

  resources :users
  
  get "about", to: 'about#index', as: :about
  get "signup", to: 'registration#new'
  post "signup", to: 'registration#create'

  post "create_post", to: 'posts#create', as: :create_secret

  get "password", to: 'passwords#edit'
  patch "password", to: 'passwords#update'
  
  get "password/reset", to: 'password_resets#new'
  post "password/reset", to: 'password_resets#create'

  get "signin", to: 'sessions#new'
  post "signin", to: 'sessions#create'
  delete "logout", to: 'sessions#destroy'

  root to: "main#index"
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :posts
    
    validates :username, presence: true, length: { maximum: 50 }, uniqueness: {case_sensitive: false}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i 
    validates :email,  presence: true, length: { maximum: 255 }, 
            format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user

    def set_current_user
        if session[:user_id]
            Current.user = User.find_by(id: session[:user_id])
        end
    end

    def require_user_logged_in!
        redirect_to signin_path, alert: "You must be signed in to do that" if Current.user.nil?
    end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
    
    def not_found
      render status: 404
    end
  
    def internal_server_error
      render status: 500
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
    end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
    
    def new
    end

    def create
        @user = User.find_by(email: params[:email])
        redirect_to root_path, notice: "This feature has not been completed yet"
    end

end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
    before_action :require_user_logged_in!

    def edit
    end

    def update
        if Current.user.update(password_params)
            redirect_to root_path, notice: "Password Updated"
        else
            render :edit
        end
    end

    def password_params
        params.require(:user).permit(:password, :password_confirmation)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    def create

        puts params
        @post = Post.new(post_params)
        user = User.find(@post[:user_id])

        if @post.save
            msg = "Thank You for Sending a Secret "
            redirect_to user, notice: msg
        else
            msg = "Secret Failed to send"
            redirect_to user, notice: msg
        end            
    end

    def post_params
        params.require(:post).permit(:user_id, :content, :pinned)
    end
end
        

app/controllers/registration_controller.rb
class RegistrationController < ApplicationController
    def new
        @user = User.new
    end

    def create

        @user = User.new(user_params)

        if @user.save
            session[:user_id] = @user.id
            msg = "Thank You for Signing Up " + @user.username
            redirect_to root_path, notice: msg
        else
            render :new
        end            
    end

    def user_params
        params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end
end
        

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        user = User.find_by(email: params[:email])

        if user.present? && user.authenticate(params[:password])
            puts "here"
            session[:user_id] = user.id
            redirect_to root_path, notice: "Logged in Succesfuly"
        else
            flash[:alert] = "Invalid email or password"
            render :new
        end

    end
    
    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: "Logged Out"
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def show
        @user = User.find(params[:id])
        @posts = @user.posts
        @new_post = Post.new
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<h1>About Me</h1>

Some more text

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Secrets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
      <%= render partial: "layouts/shared/flash" %>
      <%= render partial: "layouts/shared/navbar" %>
      
      <div class = "container">
          <%= yield %>
      </div>
  </body>
</html>

app/views/layouts/shared/_flash.html.erb
<% if flash[:notice] %>
    <div class="alert alert-info mt-4 text-center" role = "alert" margin = "auto">
        <%= flash[:notice] %>
    </div>
<% end %>
<% if flash[:alert] %>
    <div class="alert alert-info mt-4 text-center" role = "alert" margin = "auto">
        <%= flash[:alert] %>
    </div>
<% end %>

app/views/layouts/shared/_footer.html.erb
<nav class="navbar bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      Bootstrap
    </a>
  </div>
</nav>

app/views/layouts/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Secrets</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link" %>
        </li>
      </ul>

      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if Current.user %>
          <li class="nav-item">
            <span class="navbar-text">
              <%= link_to Current.user.username, password_path, class: "nav-link" %>
              </span>
          </li>
          <li class="nav-item">
            <%= button_to "Logout", logout_path, method: :delete, class: "btn btn-outline-secondary" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign Up", signup_path, class: "nav-link" %>
          </li>
            <li class="nav-item">
            <%= link_to "Sign In", signin_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
            

    
    </div>
  </div>
</nav>

app/views/main/index.html.erb
<div class="d-flex align-items-center justify-content-center">
    <h1>Welcome to Secrets</h1>

</div>

app/views/password_resets/new.html.erb
<h1> Forgot Your Password </h1>

<%= form_with url:  password_reset_path do |form| %>

    <div class="mb-3">
        <%= form.label :email %>
        <br>
        <%= form.text_field :email, class: "form_control" %>
    </div>

    <div class="mb-3" >
        <%= form.submit "Reset Password", class: "btn btn-primary"%>
    </div>
    
<% end %>

app/views/users/show.html.erb
<% provide(:title, @user.username) %> 
<h1> <%= @user.username %> ...</h1>

<% if Current.user && Current.user.id == params[:id].to_i %>
    <% if @user.posts.any? %>
        <h3> Here are your secrets</h3>
        <ul class="list-group">
            <% @user.posts.each do |post| %>
                <% puts post.content %>
                <% puts "fadsfdsaf" %>
                <li class="list-group-item"> <%= post.content %> </li>
            <% end %>
        </ul>
    <% else %>
        <% puts "here" %>
        <p> No Secrets Yet </p>
    <% end %>
<% end %>

<h3> Submit a Secret </h3>

<%= form_with model: @new_post, url: create_secret_path do |form| %>
    <% if form.object.errors.any? %>
        <div class="alert alert-danger">
            <ul>
            <% form.object.errors.full_messages.each do |message| %>
                <div><li><%= message %></li></div>
            <% end %>
            </ul>
        </div>
    <% end %>
    
    <div class="mb-3">
        <%= form.label :content %>
        <br>
        <%= form.text_field :content, class: "form_control" %>
    </div>

    <%= form.hidden_field :user_id, value: params[:id]  %>
    <%= form.hidden_field :pinned, value: false  %>

    <div class="mb-3" >
        <%= form.submit "Send Secret", class: "btn btn-primary"%>
    </div>
    
    
    

<% end %>